# Generated by Django 5.1.2 on 2024-11-08 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('img', models.FileField(upload_to='')),
                ('position', models.TextField()),
                ('cast', models.BooleanField(default=False)),
                ('crew', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_app.movie')),
            ],
        ),
    ]
